// <auto-generated />
namespace najdiPrevoz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class trips5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trips5));
        
        string IMigrationMetadata.Id
        {
            get { return "202009061549566_trips5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
