// <auto-generated />
namespace najdiPrevoz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tripss71 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tripss71));
        
        string IMigrationMetadata.Id
        {
            get { return "202009071500477_tripss71"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
